<a href="https://colab.research.google.com/github/profteachkids/CHE3022_Fall2021/blob/main/2DHeatConductionPolar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
import numpy as np
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio
pio.templates.default='plotly_dark'
from scipy.optimize import newton_krylov

In [47]:
nr, ntheta = 25, 27
dr, dtheta = 1./(nr-1), 7/4*np.pi/(ntheta-1)
r, theta = np.mgrid[1:4:(nr*1j), 0:np.pi/2:(ntheta*1j)]

T_in, T_out = 130, 150
T_plo, T_phi = 100, 150


def residual(T):
    d2r = np.zeros_like(T)
    d2theta = np.zeros_like(T)
    
    d2r[1:-1,:] = ((r[1:-1,:]+dr/2) *(T[2:,:]-T[1:-1,:]) - (r[1:-1,:]-dr/2)*(T[1:-1,:]-T[:-2,:]))/dr/dr 
    d2r[0,:]    =((r[0,:]+dr/2)*(T[1,:]-T[0,:]) - (r[0,:]-dr/2)*(T[1,:]-T_in)) /dr/dr 
    d2r[-1]   = ((r[-1,:]+dr/2)*(T_out -T[-1,:]) -(r[-1,:]-dr/2)*(T[-1,:]-T[-2,:]))/dr/dr 

    d2theta[:,1:-1] = (T[:,2:] - 2*T[:,1:-1] + T[:,:-2])/dtheta/dtheta/r[:,1:-1]
    d2theta[:,0]    = (T[:,1]  - 2*T[:,0]    + T_plo)/dtheta/dtheta/r[:,0]
    d2theta[:,-1]   = (T_phi   - 2*T[:,-1]   + T[:,-2])/dtheta/dtheta/r[:,-1]

    return d2r + d2theta

# solve
guess = np.zeros((nr, ntheta))
sol = newton_krylov(residual, guess, method='lgmres', verbose=0)

In [48]:

x,y = r*np.cos(theta), r*np.sin(theta)

fig = make_subplots()
for i in np.arange(nr):
     fig.add_trace(go.Scatter3d(x=x[i,:], y=y[i,:], z=sol[i,:], mode='lines', line_color='gray'))

for j in np.arange(ntheta):
     fig.add_trace(go.Scatter3d(x=x[:,j], y=y[:,j], z=sol[:,j], mode='lines', line_color='gray'))

fig.add_trace(go.Surface(x=x,y=y,z=sol))

fig.update_layout(width=800, height=800, scene=dict(xaxis_title='x', yaxis_title='y', zaxis_title='T'),
                  showlegend=False)

In [ ]:
ShGrid

array([[  3.15966765,   3.68627893,   4.2128902 ,   4.73950148,
          5.26611275,   5.79272403,   6.31933531,   6.84594658,
          7.37255786,   7.89916913,   8.42578041,   8.95239168,
          9.47900296,  10.00561423,  10.53222551,  11.05883678,
         11.58544806,  12.11205934,  12.63867061,  13.16528189],
       [  5.30986596,   6.19484362,   7.07982128,   7.96479894,
          8.8497766 ,   9.73475426,  10.61973192,  11.50470958,
         12.38968724,  13.2746649 ,  14.15964256,  15.04462022,
         15.92959788,  16.81457554,  17.6995532 ,  18.58453085,
         19.46950851,  20.35448617,  21.23946383,  22.12444149],
       [  7.29035914,   8.505419  ,   9.72047886,  10.93553871,
         12.15059857,  13.36565843,  14.58071828,  15.79577814,
         17.010838  ,  18.22589786,  19.44095771,  20.65601757,
         21.87107743,  23.08613728,  24.30119714,  25.516257  ,
         26.73131685,  27.94637671,  29.16143657,  30.37649643],
       [  9.16518835,  10.69271974,  

In [ ]:
ReGrid

In [ ]:
x=np.linspace(0,3,4)
y=np.linspace(5,8, 4)

In [ ]:
for i,j in zip(x,y):
    print(i,j)

0.0 5.0
1.0 6.0
2.0 7.0
3.0 8.0


In [ ]:
xx,yy = np.meshgrid(x,y)

In [ ]:
for ix, iy in zip(xx,yy):
    print(ix,iy)

[0. 1. 2. 3.] [5. 5. 5. 5.]
[0. 1. 2. 3.] [6. 6. 6. 6.]
[0. 1. 2. 3.] [7. 7. 7. 7.]
[0. 1. 2. 3.] [8. 8. 8. 8.]


In [ ]:
xx

array([[0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.],
       [0., 1., 2., 3.]])

In [ ]:
yy

array([[5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.]])

In [ ]:
xx

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [ ]:
yy

array([[5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.],
       [5., 6., 7., 8., 9.]])

In [ ]:
x=np.lin